.gitignore, changelog.md, dist/onlinebooking.js, docs/demo.css, src/booking.js, src/cssHelper.js
=> Discount alignment

changelog.md, src/booking.js, src/contactForm.js, src/cssHelper.js, src/vouchers.js
=> Don't load global CSS twice when using online bookings

changelog.md, dist/onlinebooking.js, src/cssHelper.js
Styles with the same specificity are overridden by the rule that occurs latest in the CSS, so this lets users override styles more easily
Fixes #26
=> Add styles before any user-added stylesheets

dist/onlinebooking.js, src/contactForm.js, test/js-unit/recrasContactFormSpec.js
=> If there is only 1 package and the field is required, fill it automatically

dist/onlinebooking.js, src/booking.js, test/js-unit/recrasBookingSpec.js
Refs https://gitlab.recras.nl/recras/recras/issues/6488
=> Handle 'require X per Y' requirements (not just 1 per Y)

README.md, changelog.md, dist/onlinebooking.js, docs/onlinebooking.html, src/booking.js, src/options.js, test/js-unit/karma.conf.js, test/js-unit/recrasBookingSpec.js, test/js-unit/recrasOptionsSpec.js
=> Allow selecting only a few package IDs

src/booking.js, src/options.js, test/js-unit/recrasBookingSpec.js
=> Check if max is set before giving an error

src/booking.js, test/js-unit/recrasBookingSpec.js
This will make the final PR of issue #20 a bit smaller
=> Refactor amountsValid & add test

src/booking.js
This re-applies vouchers when product amounts are changed.
Closes #50
=> Refresh total amount after applying voucher

changelog.md, src/booking.js, src/contactForm.js, src/eventHelper.js, src/vouchers.js
This fixes use of the Global Site Tag (the more modern variant of Google Analytics, possibly also used by Google Tag Manager?)
Refers to ticket 6374 in our customer ticketing system
=> Update event sending for Google Analytics

src/cssHelper.js
=> Fix amount input width in Firefox

changelog.md, src/contactForm.js, src/vouchers.js
=> Limit the number of vouchers you can buy

changelog.md, src/booking.js, src/vouchers.js
Refers to internal feature request 6598
=> Include payment amount in Analytics event

src/languageHelper.js
As referenced in https://gitlab.recras.nl/recras/recras/issues/6631
=> Fix german translation with customer's suggestion

changelog.md, src/booking.js
This allows us to send a minimum for each line (maximum was already present)
Refers to internal issue 6547
=> Use minimum quantity of a line, if it is set

src/booking.js, src/contactForm.js, src/vouchers.js
=> Enable submit buttons later, to prevent users being able to submit twice

changelog.md, src/booking.js
Fixes https://gitlab.recras.nl/recras/recras/-/issues/6717 (not publicly accessible)
=> Fix attachments not being visible when pre-filling amounts

changelog.md, src/contactForm.js, test/js-unit/recrasContactFormSpec.js
Refers to internal issue https://gitlab.recras.nl/recras/recras/-/issues/6689
=> Show customer extra fields in contact forms

src/booking.js
Refers to internal issue https://gitlab.recras.nl/recras/recras/-/issues/6731
=> Encode discount codes

src/eventHelper.js
I'm not entirely sure if this is the correct way to go, I don't know how to test this properly. I did follow the linked documentation page to come to this solution.
Fixes #96
=> Wait for google analytics to be loaded before calling getAll

src/languageHelper.js
=> Fix german translation for 'Voucher applied'

changelog.md, src/contactForm.js
Show error message in contact form in addition to general "form could not be sent" popup
=> Handle error from backend properly

changelog.md, src/contactForm.js
=> Allow dates in the past for "relation extra field"

src/contactForm.js
Refers to internal issue https://gitlab.recras.nl/recras/recras/-/issues/6995
=> Set extra field datepicker to -90, +10 years instead of -10, +10

README.md, changelog.md, src/contactForm.js, src/languageHelper.js, src/options.js, test/js-unit/recrasOptionsSpec.js
Refers to internal issue https://gitlab.recras.nl/recras/recras/-/issues/7004
=> Add `defaultCountry` option to contact forms

src/booking.js, src/vouchers.js
These errors (probably?) only occur in tests, so we should have a closer look at the tests. For real-life situations (tested on demo.recras.nl), nothing changes.
=> Fix a few test errors

src/booking.js
=> Prevent submitting the amounts form on Enter

changelog.md, src/contactForm.js, src/vouchers.js, test/js-unit/recrasContactFormSpec.js
Tested with staging:
Refers to internal issue 7137
=> Allow changing the term for number of vouchers

src/booking.js
=> Make redirect without Mollie more robust

src/eventHelper.js
Tested on a test page with our own GA4 account, events are coming in properly.
Since support for GA v2 is dropped (v3 was introduced in 2012), this is a breaking change when released
=> Remove Analytics v2 support and fix GA4 events

changelog.md, src/booking.js
=> "Number of people" incorrectly used as minimum

src/contactForm.js, src/vouchers.js
=> Contact form: show errors below the form

src/booking.js
This caused an issue where at first only half a month is visible
Refers to internal issue 7705
=> Fetch dates until the end of the month
